### ISSUE TITLE
Bug in fit_model

### ISSUE THREAD

**Issue by a-jartseva** [bioinform/ecTMB#6]
Hello,

I found a bug in the `fit_model` function, which only reveals itself if one tries to use some other name for the `trainset` variable.

Here:
https://github.com/bioinform/ecTMB/blob/abf9b3722b3688ac9857bbf3b3166ee3fc8a3ed1/R/stats.R#L412-L417
Instead of `trainset` in the CalTMB function calls (both the first argument and the `sampleN`), the argument should be `Data`, so that it refers to the argument specified in the `fit_model` function call.

It will be great if you fix it in the next release!

Best wishes,
Aleksandra

**Comment by lijingya** [comment]
Thanks. It is fixed. 

Best
Lijing
